# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Mahalanobis <- function(x, center, cov) {
    .Call(`_AISamplR_Mahalanobis`, x, center, cov)
}

dmvnorm_arma <- function(x, mean, sigma, log = FALSE) {
    .Call(`_AISamplR_dmvnorm_arma`, x, mean, sigma, log)
}

rmvnorm_arma <- function(n, mu, sigma) {
    .Call(`_AISamplR_rmvnorm_arma`, n, mu, sigma)
}

rcpp_hello_world <- function() {
    .Call(`_AISamplR_rcpp_hello_world`)
}

